### ISSUE TITLE
font with list of weights

### ISSUE THREAD

**Issue by baohouse** [millermedeiros/requirejs-plugins#64]
Let's say you want to load a font with specific weights. You could in theory do this:

require(["font!google,families:['Roboto+Condensed:300italic,400italic,400,300:latin']"]);

However, the problem is that propertyParser will split the string inside of the array brackets instead of preserving the string. So instead of the propertyParser returning an array like so:

CORRECT
["Roboto+Condensed:300italic,400italic,400,300:latin"]

it returns

CURRENT IMPLEMENTATION (BUG)
["'Roboto+Condensed:300italic", "400italic", "400", "300:latin'"]

The workaround was for me to modify the propertyParser and in the line which splits the string by comma, instead of doing that, I just pass the string into JSON.parse. Of course that means you will have to wrap each family inside quotations.

**Comment by cytRasch** [comment]
The easiest way to fix this bug is to change delimiter in your propertyBrowser.js like this:

``` javascript
function typecastVal(val){
        if (rArr.test(val)){
            val = val.replace(rArr, '$1').split('#');
        } else if (val === 'null'){
            val = null;
        } else if (val === 'false'){
            val = false;
        } else if (val === 'true'){
            val = true;
        } else if (val === '' || val === "''" || val === '""'){
            val = '';
        } else if (! isNaN(val)) {
            //isNaN('') == false
            val = +val;
        }
        return val;

   }
```

after setting a new delimiter, you just have to change the require-part into

``` javascript
require(['font!google,families:[Raleway:500,600,400,300:latin#Open+Sans:400italic,600italic,400,300,600,700:latin]']);
```

Changing the string passing to JSON.parse is probably a good solution but you have be careful with the quotations.

**Comment by baohouse** [comment]
Yeah, your solution is better for backwards compatibility.

**Comment by gerhard-boden** [comment]
Thanks a lot, needed this today. Too bad this plugin seems to discontinued, so we have to hack things together to get stuff working
