### ISSUE TITLE
json : relative path not working

### ISSUE THREAD

**Issue by adamotte** [millermedeiros/requirejs-plugins#66]
With plugin text I could do the following

```
text!../some/relative/path/file.json
```

but with json plugin this not work.

I got the error 

``` console
Uncaught SyntaxError: Unexpected token /
```

**Comment by DenisPav** [comment]
@adamotte I just had the same problem, in the end instead of this:
`
text.get(req.toUrl(name), function (data) 
`
I've changed it to:
`
text.get(name, function (data)
`
btw that line of code is in the plugin 😄
